import {findSlots,mergeSlots,localBusy} from './availability.mjs?v=all-openings-1';
const $=selector=>document.querySelector(selector);
const API=(window.TOGETHER_API||'').replace(/\/$/,'');
const tokenKey='together.session.v2',inviteKey='together.invite.v2',verifierKey='together.verifier.v2';
let bearer=sessionStorage.getItem(tokenKey)||'',me=null,friends=[],invitations=[],configured=false,serviceError='',live=null,loading=false,loadError='',version=0,week=0,showAll=false,slots=[],draft=null,saving=false;
const selected=new Set();const base=new Date();base.setHours(0,0,0,0);
const palette=[['#47705b','#e5ece5'],['#ba8355','#f3e7dc'],['#8476ac','#eae5f2'],['#5d87a0','#e3ecf2']];
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateFor=day=>{const d=new Date(base);d.setDate(d.getDate()+day);return d;};
const dateLabel=day=>dateFor(day).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'});
const time=hour=>{const mins=Math.round(hour*60);return `${Math.floor(mins/60)%12||12}${mins%60?':'+String(mins%60).padStart(2,'0'):''} ${mins>=720?'PM':'AM'}`;};
const members=()=>me?[{...me,name:'You'},...friends]:[];
const avatar=(person,index=0)=>{const [color,pale]=palette[index%palette.length];return `<span class="avatar" style="background:${pale};color:${color}">${esc(person.name.trim().slice(0,2).toUpperCase())}</span>`;};
async function api(path,input){const res=await fetch(API+path,{method:input===undefined?'GET':'POST',headers:{...(input===undefined?{}:{'Content-Type':'application/json'}),...(bearer?{Authorization:'Bearer '+bearer}:{})},body:input===undefined?undefined:JSON.stringify(input)});let data;try{data=await res.json();}catch{throw Error('The server is offline or unavailable. Please try again later.');}if(!res.ok){if(res.status===401){bearer='';sessionStorage.removeItem(tokenKey);}throw Error(data.error||'Request failed.');}return data;}
function navigate(view){for(const name of ['plan','calendars','friends'])$(`#${name}-view`).classList.toggle('hidden',name!==view);document.querySelectorAll('nav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-label').textContent={plan:'Find a time',calendars:'My calendars',friends:'Friends'}[view];}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>navigate(b.dataset.view));
function modal(title,message){$('#event-form').classList.add('hidden');$('#saved-event').classList.add('hidden');$('#modal-done').classList.remove('hidden');$('#modal-done').textContent='Got it';$('#modal-title').textContent=title;$('#modal-body').textContent=message;$('#invite-accept')?.remove();if(!$('#modal').open)$('#modal').showModal();}
const closeModal=()=>{if(!saving)$('#modal').close();};$('.close').onclick=$('#modal-done').onclick=closeModal;$('#modal').addEventListener('cancel',e=>{if(saving)e.preventDefault();});
$('#preview-info').onclick=()=>modal(me?'Your connected account':'Welcome to Together',me?`${me.name} · Only you and accepted friends can access your busy/free times. You can remove a friend or disconnect your calendar at any time.`:'Connect Google Calendar to find openings and invite friends. Appointment details are never shown to friends.');
function readBusy(id,day){const record=live?.calendars.find(c=>c.id===id);if(!record?.known)return [[0,24]];const blocks=localBusy(record.busy,dateFor(day));const now=new Date(),date=dateFor(day);if(date.toDateString()===now.toDateString())blocks.push([0,now.getHours()+now.getMinutes()/60+now.getSeconds()/3600]);else if(date<new Date(now.getFullYear(),now.getMonth(),now.getDate()))blocks.push([0,24]);return blocks;}
function renderChips(){
  $('#friend-chips').innerHTML=members().map((p,i)=>`<button class="friend-chip ${selected.has(p.id)?'selected':''}" data-person="${p.id}" aria-pressed="${selected.has(p.id)}">${avatar(p,i)}${esc(p.name)}<span class="check">${selected.has(p.id)?'✓':'+'}</span></button>`).join('')||'<span class="muted">Sign in to see your calendar and invite your people.</span>';
  document.querySelectorAll('[data-person]').forEach(b=>b.onclick=async()=>{const id=b.dataset.person;if(id===me?.id)return;selected.has(id)?selected.delete(id):selected.add(id);showAll=false;await syncCalendar();});
}
function renderCalendar(){
  $('#week-range').textContent=`${dateFor(week*7).toLocaleDateString(undefined,{month:'long',day:'numeric'})} – ${dateFor(week*7+6).toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}`;
  $('#prev-week').disabled=week===0;$('#next-week').disabled=week===1;
  let html='<div></div>';for(let i=0;i<7;i++){const d=dateFor(week*7+i);html+=`<div class="day-head ${d.toDateString()===new Date().toDateString()?'today':''}">${d.toLocaleDateString(undefined,{weekday:'short'}).toUpperCase()}<strong>${d.getDate()}</strong></div>`;}
  const start=+$('#start').value,end=+$('#end').value,span=end-start;
  const hours=Array.from({length:Math.max(0,Math.floor(span)+1)},(_,i)=>start+i);
  html+='<div class="time-gutter">'+hours.map(h=>`<span style="top:${(h-start)/span*100}%">${time(h)}</span>`).join('')+'</div>';
  const chosen=members().filter(p=>selected.has(p.id)),windows=mergeSlots(slots);
  const known=chosen.length&&!loading&&!loadError&&live&&chosen.every(p=>live.calendars.some(c=>c.id===p.id&&c.known));
  for(let i=0;i<7;i++){
    const day=week*7+i;html+=`<div class="day-column ${known?'':'unknown-column'}" style="--hour-size:${100/Math.max(1,span)}%">`;
    if(known&&span>0){
      for(const person of chosen)for(const [from,to]of readBusy(person.id,day)){
        const a=Math.max(start,from),b=Math.min(end,to);if(b<=a)continue;
        html+=`<div class="busy-block" style="left:3%;width:94%;top:${(a-start)/span*100}%;height:${(b-a)/span*100}%" title="${esc(person.name)} unavailable, ${time(a)}–${time(b)}"></div>`;
      }
      for(const window of windows.filter(w=>w.day===day))html+=`<button class="free-block" data-day="${day}" style="top:${(window.start-start)/span*100}%;height:${(window.end-window.start)/span*100}%" aria-label="Choose a time on ${dateLabel(day)}, available ${time(window.start)} to ${time(window.end)}" title="${time(window.start)}–${time(window.end)} · Tap to choose">✓</button>`;
    }
    html+='</div>';
  }
  $('#calendar').innerHTML=html;
  $('#legend').innerHTML='<span><i style="background:#d77b8d"></i>Busy / unavailable</span><span><i style="background:#e5e7e2"></i>Too short / unknown</span>';
  document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{
    const day=Number(b.dataset.day);renderResults();
    const first=document.querySelector(`[data-result-day="${day}"]`);first?.scrollIntoView({behavior:'smooth',block:'start'});first?.querySelector('button')?.focus({preventScroll:true});
  });
}
function renderResults(){
  let message=serviceError||(!me?'Connect Google Calendar to find real openings.':!me.connected?'Reconnect your calendar to find openings.':loading?'Checking everyone’s busy/free times…':loadError||(!live?'Refresh availability to find a time.':''));
  const unknown=live?.calendars.filter(c=>!c.known)||[];if(!message&&unknown.length)message='Availability is unknown for '+unknown.map(c=>members().find(p=>p.id===c.id)?.name||'a friend').join(', ')+'. Ask them to reconnect, or remove them from this search.';
  if(message||!slots.length){$('#results').innerHTML=`<div class="empty-result">${esc(message||'No opening fits everyone. Try a shorter hangout or a wider time window.')}${!me?'<button class="primary" id="result-login">Connect Google Calendar ↗</button>':''}</div>`;if($('#result-login'))$('#result-login').onclick=startLogin;return;}
  const visible=slots;const chosen=members().filter(p=>selected.has(p.id));
  $('#results').innerHTML=visible.map((s,i)=>`<article data-result-day="${s.day}" class="result ${i===0?'best':'secondary'}">${i===0?'<div class="match-label"><span></span> SOONEST SHARED OPENING</div>':''}<h3>${dateLabel(s.day)}</h3><p class="time">${time(s.start)} <small>–</small> ${time(s.end)}</p><div class="result-people">${chosen.map(p=>avatar(p,members().findIndex(m=>m.id===p.id))).join('')}<span>${chosen.length===1?'Your calendar is clear':`All ${chosen.length} of you are free`}</span></div><button data-slot="${i}">Review this plan ↗</button></article>`).join('');
  document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const slot=visible[Number(b.dataset.slot)],at=hour=>{const d=dateFor(slot.day);d.setHours(0,Math.round(hour*60),0,0);return d.toISOString();};draft={id:crypto.randomUUID().replaceAll('-',''),start:at(slot.start),end:at(slot.end),people:[...selected]};modal('Make it a plan',`${dateLabel(slot.day)}, ${time(slot.start)}–${time(slot.end)} · ${Intl.DateTimeFormat().resolvedOptions().timeZone}. Works for ${chosen.map(p=>p.name).join(', ')}. Saves to your calendar only.`);$('#event-form').classList.remove('hidden');$('#modal-done').classList.add('hidden');$('#event-title').value='Time together';$('#event-title').disabled=false;$('#event-error').textContent='';$('#save-event').disabled=false;$('#save-event').textContent='Add to my Google Calendar';});
  if($('#more'))$('#more').onclick=()=>{showAll=true;renderResults();};
}
function render(){const ready=me?.connected&&live&&!loading&&!loadError&&live.calendars.every(c=>c.known)&&[...selected].every(id=>live.calendars.some(c=>c.id===id));slots=ready?findSlots([...selected],{start:+$('#start').value,end:+$('#end').value,duration:+$('#duration').value,readBusy}):[];renderChips();renderCalendar();renderResults();}
function connectionUI(){
  $('#connection-status').textContent=serviceError?'Server unavailable':me?.connected?'Connected':configured?'Ready to connect':'Not configured';
  $('#calendar-mode').textContent=me?.connected?'Live calendar':'Not connected';$('#connect').disabled=!configured||!!serviceError;$('#connect').textContent=me?'Reconnect Google Calendar ↗':'Sign in with Google ↗';
  $('#google-setup').classList.add('hidden');$('#refresh-calendar').classList.toggle('hidden',!me?.connected);$('#disconnect').classList.toggle('hidden',!me?.connected);
  $('#preview-info').textContent=me?me.name:'Sign in to Together';$('#data-label').textContent='Busy/free only · plans save to your calendar';
  $('.results-subtitle').textContent='All matching times · start choices every 30 minutes, plus free-window boundaries. Tap green to choose a day.';$('.planner .section-heading > span').textContent='You + accepted friends';
  $('#connection-summary').textContent=me?.connected?'Connected to your primary calendar. Select friends to compare availability.':'Connect your calendar, then invite a friend to share busy/free times.';
  $('.profile strong').textContent=me?.name||'Your space';$('.profile small').textContent=me?'Google account connected':'Sign in to get started';
  $('#invite-friend').disabled=!me?.connected;document.querySelector('nav small').textContent=friends.length;
  if(me&&!$('#logout')){const b=document.createElement('button');b.id='logout';b.className='text-button';b.textContent='Sign out';b.onclick=async()=>{try{await api('/api/logout',{});}finally{bearer='';sessionStorage.removeItem(tokenKey);location.reload();}};$('.connection-actions').append(b);}if(!me)$('#logout')?.remove();
}
async function loadFriends(){if(!me){friends=[];invitations=[];renderFriends();return;}const data=await api('/api/friends');friends=data.friends;invitations=data.invitations;for(const id of selected)if(id!==me.id&&!friends.some(p=>p.id===id))selected.delete(id);renderFriends();connectionUI();}
function renderFriends(){
  $('#friends-list').innerHTML=friends.map((p,i)=>`<div class="friend-row">${avatar(p,i+1)}<div><strong>${esc(p.name)}</strong><p class="muted">${p.connected?'Sharing busy/free times':'Calendar disconnected'}</p></div><button class="text-button" data-remove="${p.id}">Remove</button></div>`).join('')||'<p class="muted">Your people will appear here when they accept an invitation.</p>';
  $('#invitations-list').innerHTML=invitations.map(p=>`<div class="friend-row"><span>Expires ${new Date(p.expires).toLocaleDateString()}</span><button class="text-button" data-revoke="${p.id}">Revoke link</button></div>`).join('')||'<p class="muted">No pending invitations.</p>';
  document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/friends/remove',{id:b.dataset.remove});await loadFriends();await syncCalendar();}catch(e){$('#friend-message').textContent=e.message;b.disabled=false;}});
  document.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('/api/invites/revoke',{id:b.dataset.revoke});$('#invite-link-box').classList.add('hidden');await loadFriends();}catch(e){$('#friend-message').textContent=e.message;b.disabled=false;}});
}
async function syncCalendar(){const current=++version;live=null;loadError='';if(!me?.connected){render();return;}loading=true;render();$('#sync-message').textContent='Checking busy/free times…';try{const end=dateFor(14),data=await api('/api/availability',{start:base.toISOString(),end:end.toISOString(),people:[...selected]});if(current!==version)return;if(data.timeMin!==base.toISOString()||data.timeMax!==end.toISOString())throw Error('Calendar coverage did not match the requested dates.');live=data;$('#sync-message').textContent='Updated '+new Date(data.syncedAt).toLocaleTimeString()+' · '+Intl.DateTimeFormat().resolvedOptions().timeZone;}catch(e){if(current!==version)return;loadError=e.message;$('#sync-message').textContent=e.message;}finally{if(current===version){loading=false;render();}}}
async function startLogin(){if(!configured){modal('Sign-in is unavailable',serviceError||'The server is not configured yet. Please try again later.');return;}$('#connect').disabled=true;try{const bytes=crypto.getRandomValues(new Uint8Array(32)),encode=b=>btoa(String.fromCharCode(...b)).replaceAll('+','-').replaceAll('/','_').replaceAll('=',''),verifier=encode(bytes),challenge=encode(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));sessionStorage.setItem(verifierKey,verifier);const data=await api('/api/auth/start',{challenge});location.assign(data.url);}catch(e){$('#sync-message').textContent=e.message;$('#connect').disabled=false;}}
$('#connect').onclick=startLogin;$('#refresh-calendar').onclick=syncCalendar;
$('#disconnect').onclick=async()=>{++version;live=null;loading=false;loadError='Disconnecting…';render();try{const data=await api('/api/disconnect',{});me.connected=false;$('#sync-message').textContent=data.revoked?'Disconnected. Friends can no longer read your calendar.':'Disconnected locally. Remove Together from Google account permissions to finish revoking access.';loadError='';connectionUI();render();}catch(e){loadError=e.message;render();}};
$('#invite-friend').onclick=async()=>{const b=$('#invite-friend');b.disabled=true;try{const invite=await api('/api/invites',{});$('#invite-link').value=invite.url;$('#invite-link-box').classList.remove('hidden');$('#friend-message').textContent='Ready to share. Your friend must sign in and accept before either calendar is shared.';await loadFriends();}catch(e){$('#friend-message').textContent=e.message;}finally{b.disabled=!me?.connected;}};
$('#copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText($('#invite-link').value);$('#friend-message').textContent='Link copied. Send it to your friend.';}catch{$('#invite-link').select();$('#friend-message').textContent='Select and copy the link above.';}};
async function showInvite(){const token=sessionStorage.getItem(inviteKey);if(!token)return;try{const invitation=await api('/api/invites/preview',{token});modal(`${invitation.name} invited you`, 'Accepting makes you friends. Both of you will be able to see each other’s busy/free times, but never appointment details. You can stop sharing by removing the friendship.');const button=document.createElement('button');button.id='invite-accept';button.className='primary';button.textContent=me?.connected?'Accept & share availability':'Sign in to accept';button.onclick=async()=>{if(!me?.connected){await startLogin();return;}button.disabled=true;try{await api('/api/invites/accept',{token});sessionStorage.removeItem(inviteKey);modal('You’re now friends.',`You and ${invitation.name} can see each other’s busy/free times. Select your friend on Find a time to compare calendars.`);await loadFriends();navigate('friends');await syncCalendar();}catch(e){$('#modal-body').textContent=e.message;button.disabled=false;}};$('#modal-done').textContent='Not now';$('#modal-done').after(button);}catch(e){sessionStorage.removeItem(inviteKey);modal('Invitation unavailable',e.message);}}
$('#event-form').onsubmit=async event=>{event.preventDefault();if(!draft||saving)return;saving=true;$('#save-event').disabled=true;$('#event-title').disabled=true;$('#save-event').textContent='Saving…';$('#event-error').textContent='';draft.title??=$('#event-title').value.trim();try{const data=await api('/api/events',draft);modal('It’s on your calendar.','Your plan is saved to your primary Google Calendar. No guests were invited and no events were added to your friends’ calendars.');$('#saved-event').href=data.url;$('#saved-event').classList.remove('hidden');draft=null;await syncCalendar();}catch(e){$('#event-error').textContent=e.message+' Retry keeps the same event ID to avoid duplicates.';$('#save-event').disabled=false;$('#save-event').textContent='Retry saving';}finally{saving=false;}};
for(const id of ['duration','start','end'])$(`#${id}`).onchange=()=>{showAll=false;render();};$('#find').onclick=async()=>{showAll=false;if(me){try{await loadFriends();}catch(e){loadError=e.message;render();return;}await syncCalendar();}else await startLogin();};$('#prev-week').onclick=()=>{week=0;renderCalendar();};$('#next-week').onclick=()=>{week=1;renderCalendar();};
async function initialize(){if(window.TOGETHER_DEPLOYMENT_PENDING){serviceError='Together is getting ready. The host needs to start the calendar-sharing service before you can sign in.';connectionUI();render();return;}const fragment=new URLSearchParams(location.hash.slice(1));if(fragment.has('invite')){sessionStorage.setItem(inviteKey,fragment.get('invite'));history.replaceState(null,'',location.pathname);}try{
  if(fragment.has('auth_code')){history.replaceState(null,'',location.pathname);const data=await api('/api/auth/exchange',{code:fragment.get('auth_code'),verifier:sessionStorage.getItem(verifierKey)});bearer=data.token;sessionStorage.setItem(tokenKey,bearer);sessionStorage.removeItem(verifierKey);}
  const status=await api('/api/status');configured=status.configured;me=status.user;if(me)selected.add(me.id);else{bearer='';sessionStorage.removeItem(tokenKey);}connectionUI();await loadFriends();render();
  if(fragment.has('auth_error')){history.replaceState(null,'',location.pathname);modal('Google sign-in did not finish','Try signing in again and approving both calendar permissions. During testing, your Google account must be added to the developer’s test-user list.');}
  if(me?.connected)await syncCalendar();await showInvite();
}catch(e){serviceError=e.message;connectionUI();render();$('#sync-message').textContent=serviceError;}}
renderFriends();render();initialize();
