import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomBytes} from 'node:crypto';
import {localStore,tokenVault} from './store.mjs';
import {socialService} from './social.mjs';

async function setup(){const store=await localStore();await store.transaction(async tx=>{for(const id of ['alice','bob','eve'])tx.set('user_'+id,{id,name:id,friends:[],tokens:'encrypted'});});return {store,social:socialService(store,'https://www.philipgheno.com/togetherapp/')};}
const tokenOf=invite=>new URL(invite.url).hash.split('=')[1];
test('accepting an invitation creates mutual friendship, including repeat acceptance',async()=>{const{social}=await setup();const invite=await social.invite('alice'),token=tokenOf(invite);assert.equal((await social.preview(token)).name,'alice');await assert.rejects(social.authorize('bob',['bob','alice']),{status:403});await social.accept('bob',token);await social.accept('bob',token);assert.equal((await social.friends('alice'))[0].id,'bob');assert.equal((await social.friends('bob'))[0].id,'alice');assert.equal((await social.authorize('bob',['bob','alice'])).length,2);await assert.rejects(social.authorize('eve',['eve','alice']),{status:403});});
test('invitation is single-use even with competing simultaneous acceptances',async()=>{const{social}=await setup();const token=tokenOf(await social.invite('alice'));const results=await Promise.allSettled([social.accept('bob',token),social.accept('eve',token)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await social.friends('alice')).length,1);});
test('self, expired, revoked and unauthorized invites are rejected',async()=>{const{social,store}=await setup();const invite=await social.invite('alice'),token=tokenOf(invite);await assert.rejects(social.accept('alice',token));await assert.rejects(social.revoke('eve',invite.id),{status:404});await social.revoke('alice',invite.id);await assert.rejects(social.accept('bob',token),{status:410});const second=await social.invite('alice');const later=socialService(store,'https://example.test/',()=>Date.now()+8*86400000);await assert.rejects(later.accept('bob',tokenOf(second)),{status:410});});
test('unfriending removes both sides and prevents reuse of accepted invitation',async()=>{const{social}=await setup();const token=tokenOf(await social.invite('alice'));await social.accept('bob',token);await social.remove('alice','bob');assert.deepEqual(await social.friends('alice'),[]);assert.deepEqual(await social.friends('bob'),[]);await assert.rejects(social.authorize('bob',['bob','alice']),{status:403});await assert.rejects(social.accept('bob',token),{status:410});});
test('tokens are encrypted and local records survive a restart',async t=>{const dir=await mkdtemp(join(tmpdir(),'together-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));const file=join(dir,'records.json'),key=randomBytes(32).toString('base64'),vault=tokenVault(key);const store=await localStore(file);const sealed=vault.seal({refresh_token:'private-token'});await store.transaction(async tx=>tx.set('user_alice',{tokens:sealed}));assert.ok(!(await readFile(file,'utf8')).includes('private-token'));const reopened=await localStore(file);assert.equal(vault.open((await reopened.get('user_alice')).tokens).refresh_token,'private-token');await assert.rejects(store.transaction(async tx=>{tx.set('bad',{x:1});throw Error('rollback');}));assert.equal(await store.get('bad'),null);});
